version: '3'
services:
  flaskapp:
    build: .
    ports:
      - "5000:5000"
    environment:
      - JWT_SECRET_KEY=supersecretkey
      - DATABASE_URL=sqlite:///licenses.db
    volumes:
      - .:/app
